# Roasts for Roast Command
roast_list = ["You're living proof that God has a sense of humor.",
              "Your body fat is about as evenly distributed as wealth in the US economy.",
              "When your mom jumped on a rainbow it rained skittles.",
              "You are the reason God created the middle finger.",
              "If your brain was dynamite, there wouldn't be enough to blow your hat off.",
              "Light travels faster than sound which is why you seemed bright until you spoke.",
              "You're so fat that when you walk you create earthquakes",
              "You eat so much that when you burp you create hurricanes",
              "Yo mama so fat, when she fell I didn't laugh, but the sidewalk cracked up.",
              "You're so fat that when you went in space there WAS no space.",
              "You're so fat that Dora the explorer cant explore you.",
              "You're as useless as 'ueue' in 'queue'.",
              "You're aura radiates 'I just stepped in water with socks on' energy.",
              "When your saying something, I can't hear you, cuz ion like the sound of nails on chalkboard.",
              "Not even jesus can save ur unholiness.",
              "May the large backpack on the bus ruin your project.",
              "Not even Blues Clues can find out how many things are wrong with you.",
              "Mirrors cant talk, luckily for you they cant laugh at you either.",
              "Hey you have something on your chin, nah the fourth one.",
              "Someday you will go far and hopefully you will stay there.",
              "I hope both sides of your pillow are warm tonight.",
              "If laughter is the solution to everything, your face must be curing everything.",
              "When I see you theres not a single thing I would change, except for the direction im looking.",
              "Were you born on the highway? Cuz that's where most accidents happen.",
              "I hope the acidity in your coffee is higher than a power plants' energy system.",
              "When your mom dropped you off at school, she got a fine for littering.",
              "I hope your voice cracks during attendance tomorrow!",
              "Maybe you should eat some makeup so you could be pretty on the inside too.",
              "You're like a cloud, when your gone the day is beautiful.",
              "You’re a grey sprinkle on a rainbow cupcake.",
              "You are more disappointing than an unsalted pretzel.",
              "Your so annoying, you made your Happy Meal cry.",
              "You have so many gaps in your teeth it looks like your tongue is in jail.",
              "I’ll never forget the first time we met. But I’ll keep trying.",
              "I forgot the world revolves around you. My apologies, how silly of me.",
              "Hold still. I’m trying to imagine you with personality.",
              "Our kid must have gotten his brain from you! I still have mine.",
              "Your face makes onions cry.",
              "911, emergency we have spotted shrek, ohh wait never mind it was you.",
              "If you’re going to be two-faced, at least make one of them pretty.",
              "I’d rather treat my baby’s diaper rash than have lunch with you.",
              "Even with McAfee my CPU crumbles in the virus that is your creativity.",
              "Where’s your off button?",
              "I’m not shy. I just don’t like you.",
              "My hair straightener is hotter than you.",
              "I have heels higher than your standards.",
              "You have more faces than Mount Rushmore.",
              "I’m jealous of people who don’t know you.",
              "You’re entitled to your incorrect opinion.",
              "I’m visualizing duct tape over your mouth.",
              "You’re the reason I prefer animals to people.",
              "I’d smack you, but that would be animal abuse.",
              "You sound reasonable… Time to up my medication.",
              "Hey, I found your nose, it’s in my business again!",
              "I might be crazy, but crazy is better than stupid.",
              "Is there an app I can download to make you disappear?",
              "90% of your ‘beauty’ could be removed with a Kleenex.",
              "The people who know me the least have the most to say.",
              "I am allergic to stupidity, so I break out in sarcasm.",
              "I didn't change. I grew up. You should try it sometime.",
              "My phone battery lasts longer than your relationships.",
              "I’m sorry that my brutal honesty was inconvenient to your ego.",
              "Some people should use a glue stick instead of chapstick.",
              "You're so free you're freer then costco samples",
              "You're so free you're freer then public restrooms",
              "You're so annoying I hope your ketchup has water in it",
              "Why are you trying to roast me? Unlike you I don't have my personality passed around like we playing"
              " a game of hot potato",
              "How can you face a problem when the problem is your face?"]
